name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-script-with-name:
    name: Run script with name
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, my name is Dmytro Tarakanov"
      
